{% set version = '0.7.1' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-simstudy
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/simstudy_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/simstudy/simstudy_{{ version }}.tar.gz
  sha256: ce2fbddc3f8dc8da0d9bb23e27349891d3e8f0e94f2f37c11a880ddf46ea2724

build:
  merge_build_host: True  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ compiler('cxx') }}            # [not win]
    - {{ compiler('m2w64_cxx') }}      # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-rcpp
    - r-backports
    - r-data.table
    - r-fastglm
    - r-glue
    - r-mvnfast
    - r-pbv
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]
    - r-rcpp
    - r-backports
    - r-data.table
    - r-fastglm
    - r-glue
    - r-mvnfast
    - r-pbv >=0.4_22

test:
  commands:
    - $R -e "library('simstudy')"           # [not win]
    - "\"%R%\" -e \"library('simstudy')\""  # [win]

about:
  home: https://github.com/kgoldfeld/simstudy, https://kgoldfeld.github.io/simstudy/, https://kgoldfeld.github.io/simstudy/dev/
  license: GPL-3.0-or-later
  summary: Simulates data sets in order to explore modeling techniques or better understand data
    generating processes. The user specifies a set of relationships between covariates,
    and generates data based on these specifications. The final data sets can represent
    data from randomized control trials, repeated measure (longitudinal) designs, and
    cluster randomized trials. Missingness can be generated using various mechanisms
    (MCAR, MAR, NMAR).
  license_family: GPL3
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'
# Type: Package

extra:
  recipe-maintainers:
    - conda-forge/r
    - lescai

# Package: simstudy
# Title: Simulation of Study Data
# Version: 0.7.1
# Date: 2023-11-22
# Authors@R: c(person(given = "Keith", family = "Goldfeld", role = c("aut", "cre"), email = "keith.goldfeld@nyulangone.org", comment = c(ORCID = "0000-0002-0292-8780")), person(given = "Jacob", family = "Wujciak-Jens", role = "aut", email = "jacob@wujciak.de", comment = c(ORCID = "0000-0002-7281-3989")))
# Description: Simulates data sets in order to explore modeling techniques or better understand data generating processes. The user specifies a set of relationships between covariates, and generates data based on these specifications. The final data sets can represent data from randomized control trials, repeated measure (longitudinal) designs, and cluster randomized trials. Missingness can be generated using various mechanisms (MCAR, MAR, NMAR).
# License: GPL-3
# URL: https://github.com/kgoldfeld/simstudy, https://kgoldfeld.github.io/simstudy/, https://kgoldfeld.github.io/simstudy/dev/
# BugReports: https://github.com/kgoldfeld/simstudy/issues
# Depends: R (>= 3.3.0)
# Imports: data.table, glue, methods, mvnfast, Rcpp, backports, fastglm
# Suggests: covr, dplyr, formatR, gee, ggplot2, grid, gridExtra, hedgehog, knitr, magrittr, Matrix, mgcv, ordinal, pracma, rmarkdown, scales, splines, survival, testthat, gtsummary, survminer, katex, dirmult, rms
# LinkingTo: Rcpp, pbv (>= 0.4-22), fastglm
# VignetteBuilder: knitr
# Encoding: UTF-8
# RoxygenNote: 7.2.3
# NeedsCompilation: yes
# Packaged: 2023-11-23 00:44:30 UTC; keith
# Author: Keith Goldfeld [aut, cre] (<https://orcid.org/0000-0002-0292-8780>), Jacob Wujciak-Jens [aut] (<https://orcid.org/0000-0002-7281-3989>)
# Maintainer: Keith Goldfeld <keith.goldfeld@nyulangone.org>
# Repository: CRAN
# Date/Publication: 2023-11-23 01:00:02 UTC
